add proxy support
projectdiscovery/asnmap pull request #10
Opened 2022-10-20 06:06 UTC by parrasajad

### Examples
socks5:
```console:
$ echo AS54115 | asnmap --proxy socks5://127.0.0.1:40932
```
http:
```console:
$ echo AS54115 | asnmap --proxy http://127.0.0.1:8080
```
input file support:
```console:
$ echo AS54115 | asnmap --proxy proxtlist.txt
```

2022-10-20 06:53 UTC, Mzack9999 requested changes
Please try to refactor the `SetProxy` method by reducing complexity and increase code readability, for example:
- Move URL checking and setproxy for each item into a proper routine
- Move the file process utility into a subroutine
- Reduce `if` nesting by preferring `err != nil` checks and early return

2022-10-20 06:53 UTC, Mzack9999 commented on libs/client.go
> +func (c *Client) SetProxy(proxyList []string) {
The signature should return an error if no valid proxy was found

2022-10-20 06:53 UTC, Mzack9999 commented on libs/client.go
> +		proxyurl, err := url.Parse(p)
I think this code can be moved into a proper function since it's repeated at line 103

2022-10-20 06:53 UTC, Mzack9999 commented on libs/client.go
> +					proxyurl, err := url.Parse(proxy)
I think this code can be moved into a proper function since it's repeated at line 82

2022-10-23 23:16 UTC, Mzack9999 approved these changes

2022-10-24 15:57 UTC, ehsandeep approved these changes

2022-10-24 15:57 UTC, merged

2022-11-12 03:19 UTC, Gitgody reviewed
Exit

2022-11-12 03:24 UTC, Gitgody commented
> ### Examples
> 
> socks5:
> 
> ```console:
> 
> $ echo AS54115 | asnmap --proxy socks5://127.0.0.1:40932
> 
> ```
> 
> http:
> 
> ```console:
> 
> $ echo AS54115 | asnmap --proxy http://127.0.0.1:8080
> 
> ```
> 
> input file support:
> 
> ```console:
> 
> $ echo AS54115 | asnmap --proxy proxtlist.txt
> 
> ```

Exit