err out bad req
projectdiscovery/asnmap pull request #356
Opened 2024-05-22 10:00 UTC by dogancanbakir

Closes #350

2024-05-22 10:04 UTC, dogancanbakir commented
ignore failing tests; flaky

2024-05-22 10:18 UTC, Mzack9999 approved these changes

2024-05-22 10:19 UTC, Mzack9999 requested changes
let's update the tests and ensure that the change from nil to error keep things working as expected

2024-05-22 13:52 UTC, Mzack9999 approved these changes

2024-06-26 20:30 UTC, ehsandeep approved these changes

2024-06-26 20:30 UTC, merged